// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://attcszqcaopibzfcsmuj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0dGNzenFjYW9waWJ6ZmNzbXVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMzQzOTAsImV4cCI6MjA2NzgxMDM5MH0.h-WgriDiv_yoy3PdwozrZ9HNALngQJpwfm5NHXBwNQU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});